import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:d_una_app/features/purchases/domain/models/models.dart';
import 'package:d_una_app/features/purchases/data/repositories/purchases_repository.dart';
import 'package:d_una_app/features/purchases/presentation/providers/purchases_providers.dart';
import 'package:d_una_app/features/purchases/data/models/purchase_item_product.dart';

class AddPurchaseState {
  final String? supplierId;
  final String? supplierName;
  final String documentType; // 'Factura' or 'Nota de entrega'
  final String? documentNumber;
  final DateTime date;
  
  final List<PurchaseItemProduct> products;
  final List<ProductSerial> serials;
  
  final bool isLoading;
  final String? error;

  AddPurchaseState({
    this.supplierId,
    this.supplierName,
    this.documentType = 'Factura',
    this.documentNumber,
    DateTime? date,
    this.products = const [],
    this.serials = const [],
    this.isLoading = false,
    this.error,
  }) : date = date ?? DateTime.now();

  double get subtotal => products.fold(0, (sum, item) => sum + item.subtotal);
  
  // TODO: Add taxation logic if necessary, for now tax is 0 or global configuration
  double get tax => 0.0;
  
  double get total => subtotal + tax;
  
  bool get hasMissingSerials {
    for (var product in products) {
       if (product.requiresSerials) {
          final count = serials.where((s) => s.productId == product.productId).length;
          if (count < product.quantity) return true;
       }
    }
    return false;
  }

  AddPurchaseState copyWith({
    String? supplierId,
    String? supplierName,
    String? documentType,
    String? documentNumber,
    DateTime? date,
    List<PurchaseItemProduct>? products,
    List<ProductSerial>? serials,
    bool? isLoading,
    String? error,
  }) {
    return AddPurchaseState(
      supplierId: supplierId ?? this.supplierId,
      supplierName: supplierName ?? this.supplierName,
      documentType: documentType ?? this.documentType,
      documentNumber: documentNumber ?? this.documentNumber,
      date: date ?? this.date,
      products: products ?? this.products,
      serials: serials ?? this.serials,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

class AddPurchaseNotifier extends StateNotifier<AddPurchaseState> {
  final PurchasesRepository _repository;

  AddPurchaseNotifier(this._repository) : super(AddPurchaseState());

  void setSupplier(String id, String name) {
    state = state.copyWith(supplierId: id, supplierName: name);
  }

  void setDocumentType(String type) {
    state = state.copyWith(documentType: type);
  }

  void setDocumentNumber(String number) {
    state = state.copyWith(documentNumber: number);
  }

  void setDate(DateTime date) {
    state = state.copyWith(date: date);
  }

  void addProduct(PurchaseItemProduct product) {
    state = state.copyWith(products: [...state.products, product]);
  }

  void updateProduct(PurchaseItemProduct product) {
    state = state.copyWith(
      products: state.products.map((p) => p.id == product.id ? product : p).toList(),
    );
  }

  void removeProduct(String productId) {
    state = state.copyWith(
      products: state.products.where((p) => p.productId != productId).toList(),
    );
  }

  void updateProductQuantity(String productId, double quantity) {
    state = state.copyWith(
      products: state.products.map((p) => 
        p.productId == productId ? p.copyWith(quantity: quantity) : p
      ).toList(),
    );
  }

  void addSerial(ProductSerial serial) {
    state = state.copyWith(serials: [...state.serials, serial]);
  }

  void removeSerial(String id) {
    state = state.copyWith(
      serials: state.serials.where((s) => s.id != id).toList(),
    );
  }

  Future<bool> createPurchase() async {
    if (state.supplierId == null) {
      state = state.copyWith(error: "Selecciona un proveedor");
      return false;
    }
    if (state.documentNumber == null || state.documentNumber!.isEmpty) {
      state = state.copyWith(error: "Ingresa el número de documento");
      return false;
    }
    if (state.products.isEmpty) {
      state = state.copyWith(error: "Agrega al menos un producto");
      return false;
    }

    try {
      state = state.copyWith(isLoading: true, error: null);
      
      final purchase = Purchase(
         id: '', // Generated by Supabase DDL
         userId: '', // Ignored/Handled by Supabase Auth
         supplierId: state.supplierId,
         documentType: state.documentType == 'Factura' ? 'invoice' : 'delivery_note',
         documentNumber: state.documentNumber!,
         date: state.date,
         subtotal: state.subtotal,
         tax: state.tax,
         total: state.total,
         hasMissingSerials: state.hasMissingSerials,
         createdAt: DateTime.now(),
         updatedAt: DateTime.now(),
      );

      // Convert products to PurchaseItem models for DB
      final dbProducts = state.products.map((PurchaseItemProduct p) => PurchaseItem(
         id: p.id,
         purchaseId: '', // To be filled by repo/DB
         productId: p.productId,
         quantity: p.quantity,
         unitPrice: p.unitPrice,
         warrantyTime: p.warrantyTime,
         warrantyUnit: p.warrantyUnit,
         requiresSerials: p.requiresSerials,
         createdAt: DateTime.now(),
         updatedAt: DateTime.now(),
      )).toList();

      // Save via repository
      await _repository.createPurchase(purchase, dbProducts, state.serials);
      
      state = state.copyWith(isLoading: false);
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, error: e.toString());
      return false;
    }
  }

  void reset() {
    state = AddPurchaseState();
  }
}

final addPurchaseProvider = StateNotifierProvider<AddPurchaseNotifier, AddPurchaseState>((ref) {
  final repository = ref.watch(purchasesRepositoryProvider);
  return AddPurchaseNotifier(repository);
});
