import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/repositories/services_repository.dart';
import '../models/service_model.dart';

class SupabaseServicesRepository implements ServicesRepository {
  final SupabaseClient _client;

  SupabaseServicesRepository(this._client);

  String get _userId => _client.auth.currentUser!.id;

  @override
  Future<List<ServiceModel>> getServices() async {
    final response = await _client
        .from('services')
        .select('*, service_rates(*), categories(*)')
        .eq('user_id', _userId)
        .order('created_at', ascending: false);

    return (response as List).map((e) => ServiceModel.fromJson(e)).toList();
  }

  @override
  Future<List<ServiceModel>> searchServices(String query) async {
    final response = await _client
        .from('services')
        .select('*, service_rates(*), categories(*)')
        .eq('user_id', _userId)
        .ilike('name', '%$query%') // You might want to search description too
        .order('created_at', ascending: false);

    return (response as List).map((e) => ServiceModel.fromJson(e)).toList();
  }

  @override
  Future<void> createService(ServiceModel service) async {
    final serviceData = service.toJson();
    serviceData.remove('id'); // ID is auto-generated by DB if UUID
    serviceData['user_id'] = _userId;
    serviceData['created_at'] = DateTime.now().toIso8601String();
    serviceData['updated_at'] = DateTime.now().toIso8601String();

    await _client.from('services').insert(serviceData);
  }

  @override
  Future<void> updateService(ServiceModel service) async {
    final serviceData = service.toJson();
    serviceData['updated_at'] = DateTime.now().toIso8601String();

    await _client.from('services').update(serviceData).eq('id', service.id);
  }

  @override
  Future<void> deleteService(String id) async {
    await _client.from('services').delete().eq('id', id);
  }
}
